### ISSUE TITLE
The Closing Bracket On Method Calls With A Block Argument Does Not Have Matching Indentation

### ISSUE THREAD

**Issue by Kurry** [square/spacecommander#13]
If you have this block of code:
```objective-c
[system presentViewControllerWithClass:[TAFOutboundSearchResultsViewController class]
                    configurationBlock:^(TAFOutboundSearchResultsViewController *outboundSearchResultsViewController) {
// TODO: Fill In Code Here
}];
```

When you run the formatter, it converts the block of code to this:
```objective-c
[system presentViewControllerWithClass:[TAFOutboundSearchResultsViewController class]
                    configurationBlock:^(TAFOutboundSearchResultsViewController *outboundSearchResultsViewController) {
// TODO: Fill In Code Here
                    }];
```

![screen shot 2015-06-30 at 1 52 07 pm](https://cloud.githubusercontent.com/assets/857247/8437874/0fb411e0-1f30-11e5-962e-c6a2ea3b6c52.png)

This issue existed in the past when I was just using a `.clang-format` file and the `clang-format` command-line tool, so I think fixing this is more of a feature request than an actual bug. Thanks again for fixing #10.

**Comment by alanf** [comment]
Yep, this looks like a `clang-format` quirk. It's matching the indentation level of the opening brace with the closing brace, and the closing `]` is coming along for the ride.

It sounds like your preferred behavior is, if there's an adjacent `}]`, and the `}` and the `]` each have preferred indentation levels that differ, the `]`'s indentation level should win?

This one sounds a bit more complex since we'd need to run a script after `clang-format` has run to find and fixup cases like this one. I'll leave this open for now, it might make sense to try to get this built into `clang-format` as well.

**Comment by Kurry** [comment]
@alanf Thanks for the help. I went ahead and created a bug report on the LLVM bugzilla here: https://llvm.org/bugs/show_bug.cgi?id=24010

**Comment by alanf** [comment]
@Kurry thank *you* for filing that in LLVM! I'm going to close this issue, but I'll keep it in mind as a possible improvement, depending on how the issue you filed goes.
